// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: deviceplugin.proto
package deviceplugin

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type SandboxService interface {
	AllocatePodDevices(context.Context, *PodRequest) (*PhysicalDeviceResponse, error)
	AllocateContainerDevices(context.Context, *ContainerRequest) (*PhysicalDeviceResponse, error)
	FreeContainerDevices(context.Context, *ContainerRequest) (*PhysicalDeviceResponse, error)
	FreePodDevices(context.Context, *PodRequest) (*PhysicalDeviceResponse, error)
}

func RegisterSandboxService(srv *ttrpc.Server, svc SandboxService) {
	srv.RegisterService("deviceplugin.Sandbox", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"AllocatePodDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PodRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AllocatePodDevices(ctx, &req)
			},
			"AllocateContainerDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.AllocateContainerDevices(ctx, &req)
			},
			"FreeContainerDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req ContainerRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FreeContainerDevices(ctx, &req)
			},
			"FreePodDevices": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req PodRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.FreePodDevices(ctx, &req)
			},
		},
	})
}

type sandboxClient struct {
	client *ttrpc.Client
}

func NewSandboxClient(client *ttrpc.Client) SandboxService {
	return &sandboxClient{
		client: client,
	}
}

func (c *sandboxClient) AllocatePodDevices(ctx context.Context, req *PodRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "deviceplugin.Sandbox", "AllocatePodDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *sandboxClient) AllocateContainerDevices(ctx context.Context, req *ContainerRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "deviceplugin.Sandbox", "AllocateContainerDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *sandboxClient) FreeContainerDevices(ctx context.Context, req *ContainerRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "deviceplugin.Sandbox", "FreeContainerDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *sandboxClient) FreePodDevices(ctx context.Context, req *PodRequest) (*PhysicalDeviceResponse, error) {
	var resp PhysicalDeviceResponse
	if err := c.client.Call(ctx, "deviceplugin.Sandbox", "FreePodDevices", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
